# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc3f777cf647645af929526c01f4543ff1c753378e1c7208d603e55897900d7ac0bffd1e3d6529e5c0b7c8f7c5c7938ba7f2aff3475f62166c2a54153a519377

test:
  secret_key_base: 1f899c0726e6fde858893a4102d66a098afe6c769f101eba5bc89ce319c595e0e92c5176164d6cd0dd2641701f9bc2571b1ad00dd9f6fd532c69ed11f82e6790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
